# Numpy

### Importing

In [1]:
import numpy as np

### Create and Multipy Numpy Array

In [2]:
l = [1, 2, 3]
l1 = [4, 5, 6]
np_list = np.array(l)
np_list1 = np.array(l1)
np_list2 = np_list * np_list1

np_list2

array([ 4, 10, 18])

### Numpy Array Item Type

In [3]:
# only contains same type
arr = np.array([1.5, True])
arr1 = np.array([1.5, True, "Samet"])
print(arr)
print(arr1)

[1.5 1. ]
['1.5' 'True' 'Samet']


### Array Dimensions

In [4]:
two_d = np.array([[1,2,3], [1,2,3]])
print(two_d.shape)
print(two_d[:, 0:2])

(2, 3)
[[1 2]
 [1 2]]


### Generate Data

In [5]:
height = np.random.normal(1.72, 0.20, 500)
weight = np.random.normal(65, 20, 500)

np_city = np.round(np.column_stack([height, weight]), 2)
np_city[:, 0]

array([2.15, 1.69, 1.62, 1.74, 1.51, 1.42, 1.97, 1.81, 2.14, 1.37, 1.82,
       1.57, 1.82, 1.77, 1.66, 1.99, 1.6 , 1.34, 1.65, 1.86, 1.49, 1.9 ,
       1.67, 1.74, 1.68, 1.85, 1.75, 1.84, 1.76, 1.95, 1.83, 1.47, 1.85,
       1.8 , 1.69, 1.87, 1.6 , 1.61, 1.6 , 1.93, 1.54, 1.8 , 1.61, 1.87,
       1.82, 1.49, 1.64, 1.3 , 1.82, 1.79, 1.64, 2.18, 1.9 , 1.73, 1.64,
       1.55, 1.74, 1.74, 1.99, 1.56, 1.52, 1.79, 1.88, 1.7 , 2.01, 1.62,
       1.61, 1.77, 1.84, 1.89, 1.55, 1.86, 1.95, 1.85, 1.91, 1.8 , 1.62,
       1.65, 1.39, 1.73, 1.93, 1.59, 1.76, 1.99, 1.33, 1.91, 1.4 , 1.89,
       1.48, 1.52, 1.61, 1.89, 1.58, 1.89, 1.61, 1.53, 1.43, 1.5 , 1.56,
       1.65, 1.79, 1.4 , 1.58, 1.41, 1.53, 1.83, 1.74, 1.55, 1.77, 1.55,
       1.77, 1.81, 1.65, 1.84, 1.93, 1.67, 1.91, 1.88, 1.57, 1.84, 1.82,
       1.96, 1.94, 1.5 , 1.52, 1.74, 1.73, 1.58, 1.38, 1.63, 1.76, 1.8 ,
       1.62, 1.54, 1.94, 2.19, 1.62, 1.63, 1.73, 1.49, 1.67, 2.  , 1.96,
       2.13, 1.68, 1.7 , 1.99, 1.99, 1.98, 1.55, 1.

### Comparing Numpy Array

In [6]:
ages = np.array([11, 18, 19, 32, 7, 49, 23, 35])
print(ages > 18)

[False False  True  True False  True  True  True]


In [7]:
print(ages[ages > 18])

[19 32 49 23 35]


In [8]:
print(np.logical_and(ages > 18, ages < 30))
print(ages[np.logical_and(ages > 18, ages < 30)])

[False False  True False False False  True False]
[19 23]


### Loop Arrays

In [ ]:
l = ["a", "b", "c"]
for index, val in enumerate(l):
    print(index, val)

#### Numpy Array

In [9]:
for val in ages:
    print(val)

11
18
19
32
7
49
23
35


#### 2D Numpy Array

In [10]:
for val in np_city:
    print(val)

[ 2.15 50.51]
[ 1.69 37.49]
[ 1.62 54.75]
[ 1.74 41.77]
[ 1.51 74.79]
[ 1.42 19.86]
[  1.97 108.09]
[ 1.81 62.58]
[ 2.14 57.38]
[ 1.37 88.78]
[ 1.82 95.74]
[ 1.57 50.91]
[ 1.82 39.4 ]
[ 1.77 71.59]
[ 1.66 72.4 ]
[ 1.99 98.58]
[ 1.6  49.22]
[ 1.34 56.82]
[  1.65 101.42]
[ 1.86 66.69]
[ 1.49 58.06]
[ 1.9  82.15]
[ 1.67 96.15]
[ 1.74 67.75]
[ 1.68 36.29]
[ 1.85 77.58]
[ 1.75 35.05]
[ 1.84 22.43]
[ 1.76 31.72]
[ 1.95 44.71]
[1.83 6.92]
[ 1.47 86.78]
[  1.85 123.16]
[ 1.8  34.99]
[ 1.69 54.92]
[ 1.87 73.56]
[ 1.6  50.16]
[ 1.61 53.2 ]
[ 1.6  76.84]
[ 1.93 56.24]
[ 1.54 92.87]
[ 1.8  77.44]
[  1.61 101.21]
[ 1.87 58.62]
[ 1.82 63.12]
[ 1.49 62.31]
[1.64 9.83]
[ 1.3  66.16]
[ 1.82 69.02]
[  1.79 102.79]
[ 1.64 67.54]
[ 2.18 47.97]
[ 1.9  48.58]
[ 1.73 45.52]
[ 1.64 98.34]
[ 1.55 70.39]
[ 1.74 92.66]
[ 1.74 76.25]
[ 1.99 27.49]
[ 1.56 60.36]
[ 1.52 28.49]
[ 1.79 51.54]
[ 1.88 58.13]
[ 1.7 61.2]
[ 2.01 41.44]
[ 1.62 32.14]
[ 1.61 68.49]
[ 1.77 27.33]
[ 1.84 46.44]
[ 1.89 83.33]
[  1.55 106.05]


In [11]:
for val in np.nditer(np_city):
    print(val)

2.15
50.51
1.69
37.49
1.62
54.75
1.74
41.77
1.51
74.79
1.42
19.86
1.97
108.09
1.81
62.58
2.14
57.38
1.37
88.78
1.82
95.74
1.57
50.91
1.82
39.4
1.77
71.59
1.66
72.4
1.99
98.58
1.6
49.22
1.34
56.82
1.65
101.42
1.86
66.69
1.49
58.06
1.9
82.15
1.67
96.15
1.74
67.75
1.68
36.29
1.85
77.58
1.75
35.05
1.84
22.43
1.76
31.72
1.95
44.71
1.83
6.92
1.47
86.78
1.85
123.16
1.8
34.99
1.69
54.92
1.87
73.56
1.6
50.16
1.61
53.2
1.6
76.84
1.93
56.24
1.54
92.87
1.8
77.44
1.61
101.21
1.87
58.62
1.82
63.12
1.49
62.31
1.64
9.83
1.3
66.16
1.82
69.02
1.79
102.79
1.64
67.54
2.18
47.97
1.9
48.58
1.73
45.52
1.64
98.34
1.55
70.39
1.74
92.66
1.74
76.25
1.99
27.49
1.56
60.36
1.52
28.49
1.79
51.54
1.88
58.13
1.7
61.2
2.01
41.44
1.62
32.14
1.61
68.49
1.77
27.33
1.84
46.44
1.89
83.33
1.55
106.05
1.86
45.05
1.95
38.1
1.85
52.41
1.91
65.38
1.8
81.33
1.62
51.36
1.65
109.35
1.39
81.29
1.73
80.77
1.93
81.6
1.59
68.12
1.76
108.97
1.99
67.75
1.33
82.29
1.91
51.03
1.4
79.46
1.89
96.67
1.48
62.85
1.52
56.46
1.61
56.89
1.89
103.8