# Numpy

### Importing

In [4]:
import numpy as np

### Create and Multipy Numpy Array

In [5]:
l = [1, 2, 3]
l1 = [4, 5, 6]
np_list = np.array(l)
np_list1 = np.array(l1)
np_list2 = np_list * np_list1

np_list2

array([ 4, 10, 18])

### Numpy Array Item Type

In [6]:
# only contains same type
arr = np.array([1.5, True])
arr1 = np.array([1.5, True, "Samet"])
print(arr)
print(arr1)

[1.5 1. ]
['1.5' 'True' 'Samet']


### Array Dimensions

In [7]:
two_d = np.array([[1,2,3], [1,2,3]])
print(two_d.shape)
print(two_d[:, 0:2])

(2, 3)
[[1 2]
 [1 2]]


### Generate Data

In [11]:
height = np.random.normal(1.72, 0.20, 500)
weight = np.random.normal(65, 20, 500)

np_city = np.round(np.column_stack([height, weight]), 2)
np_city[:, 0]

array([1.85, 1.49, 1.56, 1.61, 2.11, 1.19, 1.76, 1.84, 1.98, 1.76, 1.62,
       1.67, 1.16, 1.98, 1.61, 1.93, 1.71, 1.86, 1.47, 1.78, 1.39, 1.83,
       2.01, 2.09, 1.76, 1.51, 1.61, 1.72, 1.69, 1.61, 1.46, 1.96, 1.42,
       1.87, 2.07, 1.75, 1.79, 1.88, 1.6 , 1.89, 1.78, 1.87, 2.07, 1.7 ,
       1.6 , 1.82, 1.84, 1.76, 1.8 , 1.54, 1.95, 1.49, 1.51, 1.89, 1.81,
       1.51, 1.76, 1.79, 2.33, 1.65, 1.9 , 1.9 , 1.69, 1.73, 1.4 , 1.39,
       1.91, 1.77, 1.68, 1.52, 1.93, 2.33, 1.66, 1.52, 1.77, 1.62, 1.67,
       1.72, 1.73, 1.59, 1.93, 1.58, 1.64, 1.52, 2.08, 1.73, 1.26, 1.64,
       1.48, 1.38, 1.79, 1.63, 1.63, 1.58, 1.76, 1.72, 1.81, 1.35, 1.72,
       1.62, 1.99, 1.24, 1.78, 1.74, 1.99, 1.77, 1.98, 1.09, 1.62, 1.59,
       1.64, 1.57, 1.76, 1.27, 1.46, 1.64, 1.97, 1.82, 1.34, 1.76, 1.41,
       1.73, 2.27, 1.86, 1.64, 1.5 , 1.72, 1.57, 1.72, 1.67, 1.67, 1.74,
       1.62, 1.7 , 1.92, 1.54, 1.69, 1.68, 1.8 , 1.9 , 1.61, 1.78, 1.63,
       1.56, 1.98, 1.69, 1.74, 1.62, 1.64, 1.85, 1.