# Numpy

### Importing

In [15]:
import numpy as np

### Create and Multipy Numpy Array

In [16]:
l = [1, 2, 3]
l1 = [4, 5, 6]
np_list = np.array(l)
np_list1 = np.array(l1)
np_list2 = np_list * np_list1

np_list2

array([ 4, 10, 18])

### Numpy Array Item Type

In [17]:
# only contains same type
arr = np.array([1.5, True])
arr1 = np.array([1.5, True, "Samet"])
print(arr)
print(arr1)

[1.5 1. ]
['1.5' 'True' 'Samet']


### Array Dimensions

In [18]:
two_d = np.array([[1,2,3], [1,2,3]])
print(two_d.shape)
print(two_d[:, 0:2])

(2, 3)
[[1 2]
 [1 2]]


### Generate Data

In [19]:
height = np.random.normal(1.72, 0.20, 500)
weight = np.random.normal(65, 20, 500)

np_city = np.round(np.column_stack([height, weight]), 2)
np_city[:, 0]

array([1.41, 1.61, 1.73, 1.53, 1.86, 1.81, 1.91, 1.96, 1.76, 1.86, 1.48,
       1.77, 1.52, 1.47, 1.48, 1.97, 1.82, 1.99, 1.63, 1.78, 1.64, 1.94,
       2.06, 1.74, 1.83, 2.04, 2.02, 1.83, 1.75, 2.07, 1.6 , 1.21, 1.94,
       2.02, 1.32, 1.88, 1.61, 1.69, 1.67, 1.57, 1.88, 1.7 , 1.68, 1.42,
       1.25, 1.58, 1.82, 1.38, 1.73, 1.82, 1.55, 1.65, 1.92, 1.7 , 1.72,
       1.81, 1.66, 1.69, 1.95, 1.59, 2.21, 1.69, 1.95, 1.94, 1.59, 1.89,
       1.69, 1.77, 1.7 , 1.98, 1.85, 1.72, 1.79, 1.76, 2.07, 2.08, 1.81,
       1.53, 1.96, 1.86, 2.  , 1.32, 1.94, 1.96, 1.6 , 1.85, 1.47, 1.9 ,
       1.48, 1.66, 1.61, 1.77, 1.54, 2.03, 1.15, 1.69, 1.84, 1.72, 1.53,
       1.54, 1.77, 2.01, 1.76, 1.79, 1.15, 1.75, 1.47, 1.81, 1.57, 1.82,
       1.82, 1.35, 2.14, 1.57, 1.97, 1.8 , 1.22, 1.71, 1.87, 1.77, 1.5 ,
       1.74, 1.3 , 2.14, 1.71, 1.67, 1.59, 1.44, 1.63, 1.67, 1.77, 1.76,
       1.51, 1.94, 1.93, 1.73, 1.67, 1.57, 1.37, 1.72, 1.57, 1.83, 1.47,
       1.75, 1.49, 1.59, 1.71, 2.07, 1.74, 1.81, 2.

### Comparing Numpy Array

In [20]:
ages = np.array([11, 18, 19, 32, 7, 49, 23, 35])
print(ages > 18)

[False False  True  True False  True  True  True]


In [21]:
print(ages[ages > 18])

[19 32 49 23 35]


In [22]:
print(np.logical_and(ages > 18, ages < 30))
print(ages[np.logical_and(ages > 18, ages < 30)])

[False False  True False False False  True False]
[19 23]


### Loop Arrays

In [23]:
l = ["a", "b", "c"]
for index, val in enumerate(l):
    print(index, val)

0 a
1 b
2 c


#### Numpy Array

In [24]:
for val in ages:
    print(val)

11
18
19
32
7
49
23
35


#### 2D Numpy Array

In [25]:
for val in np_city:
    print(val)

[ 1.41 85.23]
[ 1.61 63.49]
[  1.73 105.06]
[ 1.53 50.61]
[ 1.86 91.38]
[  1.81 101.  ]
[ 1.91 64.66]
[ 1.96 73.03]
[ 1.76 65.59]
[ 1.86 77.34]
[ 1.48 77.42]
[ 1.77 74.62]
[ 1.52 49.64]
[ 1.47 59.88]
[ 1.48 50.61]
[ 1.97 64.32]
[ 1.82 54.72]
[ 1.99 44.7 ]
[ 1.63 54.68]
[ 1.78 54.94]
[ 1.64 34.88]
[ 1.94 19.26]
[ 2.06 55.1 ]
[ 1.74 83.1 ]
[ 1.83 74.95]
[ 2.04 51.16]
[ 2.02 79.92]
[ 1.83 75.93]
[ 1.75 96.99]
[ 2.07 71.77]
[ 1.6  71.76]
[ 1.21 71.59]
[ 1.94 75.43]
[ 2.02 79.36]
[ 1.32 87.89]
[ 1.88 82.13]
[ 1.61 76.55]
[ 1.69 22.74]
[ 1.67 47.17]
[ 1.57 68.9 ]
[ 1.88 68.52]
[  1.7  107.76]
[ 1.68 71.58]
[ 1.42 36.5 ]
[ 1.25 65.07]
[ 1.58 32.72]
[ 1.82 73.92]
[ 1.38 84.49]
[ 1.73 34.27]
[ 1.82 68.87]
[ 1.55 36.19]
[ 1.65 73.41]
[ 1.92 60.88]
[ 1.7  61.55]
[ 1.72 62.91]
[ 1.81 62.37]
[ 1.66 70.11]
[ 1.69 63.05]
[ 1.95 61.74]
[ 1.59 59.15]
[ 2.21 58.7 ]
[ 1.69 57.54]
[ 1.95 63.98]
[ 1.94 60.48]
[ 1.59 44.34]
[ 1.89 58.4 ]
[ 1.69 30.19]
[ 1.77 43.13]
[ 1.7  37.88]
[ 1.98 49.33]
[ 1.85 61.25]


In [26]:
for val in np.nditer(np_city):
    print(val)

1.41
85.23
1.61
63.49
1.73
105.06
1.53
50.61
1.86
91.38
1.81
101.0
1.91
64.66
1.96
73.03
1.76
65.59
1.86
77.34
1.48
77.42
1.77
74.62
1.52
49.64
1.47
59.88
1.48
50.61
1.97
64.32
1.82
54.72
1.99
44.7
1.63
54.68
1.78
54.94
1.64
34.88
1.94
19.26
2.06
55.1
1.74
83.1
1.83
74.95
2.04
51.16
2.02
79.92
1.83
75.93
1.75
96.99
2.07
71.77
1.6
71.76
1.21
71.59
1.94
75.43
2.02
79.36
1.32
87.89
1.88
82.13
1.61
76.55
1.69
22.74
1.67
47.17
1.57
68.9
1.88
68.52
1.7
107.76
1.68
71.58
1.42
36.5
1.25
65.07
1.58
32.72
1.82
73.92
1.38
84.49
1.73
34.27
1.82
68.87
1.55
36.19
1.65
73.41
1.92
60.88
1.7
61.55
1.72
62.91
1.81
62.37
1.66
70.11
1.69
63.05
1.95
61.74
1.59
59.15
2.21
58.7
1.69
57.54
1.95
63.98
1.94
60.48
1.59
44.34
1.89
58.4
1.69
30.19
1.77
43.13
1.7
37.88
1.98
49.33
1.85
61.25
1.72
78.64
1.79
47.87
1.76
60.65
2.07
10.75
2.08
59.66
1.81
69.01
1.53
81.92
1.96
86.57
1.86
46.55
2.0
46.67
1.32
48.89
1.94
50.81
1.96
50.54
1.6
54.16
1.85
58.0
1.47
94.85
1.9
75.1
1.48
63.2
1.66
69.81
1.61
17.32
1.77
71.0
1.54

### Transpose

In [27]:
# transpose numpy array
np_arr = np.array([[1, 3, 5], [2, 4, 6]])
print(np_arr)
np_arr_t = np.transpose(np_arr)
print(np_arr_t)

[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]


### Random

In [28]:
np.random.seed(123)
print(np.random.rand())
print(np.random.randint(1, 5))
print(np.random.randint(1, 5))
# always first and second numbers equal 2 and 3, if you assign seed to 123

0.6964691855978616
3
3
